version: '3'
services:
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        image: frt/gps_db
        container_name: gps_db
        volumes:
             - ./db/sql:/docker-entrypoint-initdb.d
             #- ./db/data:/var/lib/mysql
             - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    
    mobile:
        build:
            context: ./mobile
            dockerfile: Dockerfile
        image: frt/gps_mobile
        container_name: gps_mobile
        ports:
            - 8080:8080
